### ISSUE TITLE
Revocation Service Implementation

### ISSUE THREAD

**Issue by mustafasalfiti** [cre8/wallet#24]

**Comment by cre8** [comment]
We should follow this [RFC](https://www.ietf.org/archive/id/draft-looker-oauth-jwt-cwt-status-list-01.html)

- Right now the issuer does not track the issued credentials, this is relevant for him to revoke them
- The oid4vp instance can be passed a revocationcheck function, but I am not sure if it i already compliant to sd-jwt-vc. If not, we can validate the revocation inside the normal validation function.
- The wallet backend can check the revocation in an interval or each time the credential gets requested from the server

**Comment by cre8** [comment]
PR is out to the [sd-jwt-vc](https://github.com/openwallet-foundation-labs/sd-jwt-js/pull/225). Once this is merged, we can use the next version and implement it.

**Comment by cre8** [comment]
The wallet should check in an interval if a credential is still valid. If not, a flag needs to be set in the DB to show the user that the credential got revoked. We should then move it to the archive since the credential can not be used for presentation anymore
